sudo: required

language: go

services:
  - docker

go:
  - 1.7

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}

before_install:
  - go get github.com/onsi/ginkgo/ginkgo
  - go get github.com/onsi/gomega

install:
  - go get -v ./...

script:
  - ginkgo -r -v

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o hirondelle .;
    docker build -t pabardina/hirondelle-api .;
    docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD;
    docker push pabardina/hirondelle-api;
    fi

before_deploy:
  - openssl aes-256-cbc -K $encrypted_240c9adf9767_key -iv $encrypted_240c9adf9767_iv
    -in deployment/deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa

deploy:
  - provider: script
    script: ssh -o "StrictHostKeyChecking no" $SSH_USER@$SSH_ADDRESS './deploy.sh'
    on:
      branch: master
